import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./navbar";
import { AuthProvider } from "@/contexts/AuthContext";
import { Yatra_One } from "next/font/google";
import { Toaster } from "sonner";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const yatraOne = Yatra_One({
  weight: "400",
  variable: "--font-yatra-one",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} ${yatraOne.variable}  antialiased`}>
          <Navbar />
          {children}
          <Toaster position="top-left" dir="rtl" />
        </body>
      </html>
    </AuthProvider>
  );
}
