name: Secret Scanning

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  secrets-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download GitLeaks CLI
        run: |
          curl -sSL https://github.com/gitleaks/gitleaks/releases/download/v8.18.2/gitleaks_8.18.2_linux_x64.tar.gz -o gitleaks.tar.gz
          tar -xzf gitleaks.tar.gz
          chmod +x gitleaks
          sudo mv gitleaks /usr/local/bin/

      - name: Run GitLeaks Secret Scan
        run: |
          gitleaks detect \
            --source . \
            --config .github/gitleaks.toml \
            --no-git \
            --verbose
