name: Secret Scanning

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  secrets-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run GitLeaks Secret Scan
        uses: gitleaks/gitleaks-action@v2
        with:
          config-path: .github/gitleaks.toml
          fail-on-detection: true
